# Generated by Django 4.1.2 on 2022-10-15 16:36

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_merge_20220416_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('meeting_time', models.DateTimeField()),
                ('semester', models.CharField(default='Fall', max_length=100, verbose_name=main.models.SEMESTER_CHOICE)),
                ('year', models.IntegerField(default=2022)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('length', models.IntegerField()),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main.class')),
            ],
        ),
    ]
