# Generated by Django 4.1.2 on 2022-10-15 16:43

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_class_semester_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='blah', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.CharField(default='Fall', max_length=100, verbose_name=main.models.SEMESTER_CHOICE),
        ),
    ]
