# Generated by Django 4.1.2 on 2022-10-16 06:10

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_phonenumber_alter_class_semester_alter_test_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.CharField(default='Fall', max_length=100, verbose_name=main.models.SEMESTER_CHOICE),
        ),
    ]
