# Generated by Django 4.1.2 on 2022-10-16 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_rename_class_name_class_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Send',
        ),
        migrations.AlterField(
            model_name='class',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.CharField(default='Fall', max_length=100, verbose_name=main.models.SEMESTER_CHOICE),
        ),
    ]
