# Generated by Django 4.1.2 on 2022-10-16 17:07

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_test_date_alter_test_starts_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.CharField(default=0, max_length=100, verbose_name=main.models.SEMESTER_CHOICE),
        ),
    ]
