# Generated by Django 4.1.2 on 2022-10-16 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_test_post_survey_sent_test_pre_survey_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.TextField(choices=[(0, 'F'), (1, 'D'), (2, 'C'), (3, 'B'), (4, 'A')])),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
