# Generated by Django 4.1.2 on 2022-10-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='confidence',
            field=models.TextField(choices=[(0, 'Not Really'), (1, 'Meh'), (2, 'Yeah')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='do_my_best',
            field=models.TextField(choices=[(0, 'Not Really'), (1, 'Meh'), (2, 'Yeah')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='prepared_well',
            field=models.TextField(choices=[(0, 'Not Really'), (1, 'Meh'), (2, 'Yeah')], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='confidence',
            field=models.IntegerField(choices=[(0, 'Not Really'), (1, 'Meh'), (2, 'Yeah')]),
        ),
    ]
